apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eshop.fullname" . }}
  namespace: {{ .Values.globalnamespaceName | default "app" }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "eshop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eshop.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: ConnectionStrings__IdentityDB
              valueFrom:
                secretKeyRef:
                  name: {{ include "eshop.fullname" . }}-secrets
                  key: IDENTITYDB_CONNECTION
            - name: ConnectionStrings__EventBus
              valueFrom:
                secretKeyRef:
                  name: {{ include "eshop.fullname" . }}-secrets
                  key: EVENTBUS_CONNECTION
          volumeMounts:
            - name: data-protection-keys
              mountPath: /root/.aspnet/data-protection-keys
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data-protection-keys
          persistentVolumeClaim:
            claimName: {{ include "eshop.fullname" . }}-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "eshop.fullname" . }}-pvc
  namespace: {{ .Values.globalnamespaceName | default "app" }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
