apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "identity.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "identity.name" . }}
    spec:
      containers:
        - name: identity-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "identity.fullname" . }}-config
            - secretRef:
                name: {{ include "identity.fullname" . }}-secrets
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: datakeys
              mountPath: {{ .Values.volumes.mountPath }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: datakeys
          hostPath:
            path: {{ .Values.volumes.hostPath }}
