apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity.fullname" . }}-secrets
type: Opaque
stringData:
  ConnectionStrings__IdentityDB: {{ .Values.env.ConnectionStrings__IdentityDB | quote }}
  ConnectionStrings__EventBus: {{ .Values.env.ConnectionStrings__EventBus | quote }}
