{{- if .Values.serviceAccount }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.serviceAccount.name }}
           {{ .Values.serviceAccount.name }}
         {{ else }}
           {{ include "identity-api.fullname" . }}
         {{ end }}
  labels:
    app.kubernetes.io/name: {{ include "identity-api.name" . }}
    helm.sh/chart: {{ include "identity-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
{{- end }}
