apiVersion: v1
kind: Service
metadata:
  name: {{ include "eshop.fullname" . }}
  namespace: {{ .Values.global.namespace | default "app" }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "eshop.selectorLabels" . | nindent 4 }}
