apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: dev 
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 5004
    targetPort: 5004
    nodePort: 31689
  type: NodePort
