Vagrant.configure("2") do |config|
  # ========================================
  # BOX UBUNTU
  # ========================================
  config.vm.box = "bento/ubuntu-22.04"

  # ========================================
  # KUBE CONTROL PLANE
  # ========================================
  config.vm.define "kube-control" do |control|
    control.vm.hostname = "kube-control"
    control.vm.network "private_network",
      ip: "192.168.57.10"

    control.vm.provider "vmware_desktop" do |v|
      v.gui = false
      v.vmx["displayname"] = "eshop-kube-control"
      v.vmx["memsize"] = "3072"
      v.vmx["numvcpus"] = "2"
    end
  end

  # ========================================
  # KUBE WORKER
  # ========================================
  config.vm.define "kube-worker" do |worker|
    worker.vm.hostname = "kube-worker"
    worker.vm.network "private_network",
      ip: "192.168.57.11"

    worker.vm.provider "vmware_desktop" do |v|
      v.gui = false
      v.vmx["displayname"] = "eshop-kube-worker"
      v.vmx["memsize"] = "6144"
      v.vmx["numvcpus"] = "2"
    end
  end
end
