Vagrant.configure("2") do |config|
  # ========================================
  # BOX UBUNTU
  # ========================================
  config.vm.box = "ubuntu/jammy64"

  # ========================================
  # KUBE CONTROL PLANE
  # ========================================
  config.vm.define "kube-control" do |control|
    control.vm.hostname = "kube-control"
    control.vm.network "private_network",
      ip: "192.168.57.10"

    control.vm.provider "virtualbox" do |vb|
      vb.name = "eshop-kube-control"
      vb.memory = 3072
      vb.cpus = 2
    end
  end


  # ========================================
  # KUBE WORKER
  # ========================================
  config.vm.define "kube-worker" do |worker|
    worker.vm.hostname = "kube-worker"
    worker.vm.network "private_network",
      ip: "192.168.57.11"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "eshop-kube-worker"
      vb.memory = 2048
      vb.cpus = 2
    end
  end

end
