```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "Webhooks-chart.fullname" . }}
  namespace: {{ .Values.global.namespace | default "dev" }}
  labels:
    {{- include "Webhooks-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "Webhooks-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "Webhooks-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          command: ["/bin/sh", "-c", "./wait-for-it.sh rabbitmq:5672 -- ./wait-for-it.sh catalogdb:5432 -- dotnet Webhooks.API.dll"]
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: ConnectionStrings__Webhooks
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: WEBHOOKSDB_CONNECTION
            - name: ConnectionStrings__EventBus
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: EVENTBUS_CONNECTION
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
```