apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eshop.fullname" . }}-secrets
  namespace: {{ .Values.globalnamespaceName | default "app" }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
type: Opaque
data:
  EVENTBUS_CONNECTION: {{ .Values.secret.EVENTBUS_CONNECTION | b64enc }}
  ORDERINGDB_CONNECTION: {{ .Values.secret.ORDERINGDB_CONNECTION | b64enc }}
