apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.headlessService.name }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
