apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /mnt/data/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-172-31-18-201
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
