apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eshop-catalogdb
  namespace: dev
  labels:
    app.kubernetes.io/name: catalogdb
    helm.sh/chart: catalogdb-0.1.0
    app.kubernetes.io/instance: eshop
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: eshop-catalogdb-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalogdb
      app.kubernetes.io/instance: eshop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalogdb
        app.kubernetes.io/instance: eshop
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: catalogdb
          image: ankane/pgvector:latest
          imagePullPolicy: IfNotPresent
          command:
            - postgres
            - -c
            - shared_buffers=512MB
            - -c
            - max_connections=200
            - -c
            - fsync=off
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_DB
              value: "catalogdb"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eshop-catalogdb-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init-db.sh
              subPath: init-db.sh
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - catalogdb
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - catalogdb
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: init-script
          configMap:
            name: eshop-catalogdb-init-script
            items:
              - key: init-db.sh
                path: init-db.sh
                mode: 0755
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: 
        resources:
          requests:
            storage: 1Gi
