enabled: true
replicas: 1
image: redis:7.2-alpine
imagePullPolicy: IfNotPresent
containerPort: 6379
servicePort: 6379
serviceType: ClusterIP
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
livenessProbe:
  exec:
    command: ["redis-cli", "ping"]
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  exec:
    command: ["redis-cli", "ping"]
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
persistence:
  enabled: true
  size: 1Gi
command:
  - redis-server
  - --save ""
  - --appendonly no
  - --maxmemory 256mb
  - --maxmemory-policy allkeys-lru
secret:
  REDIS_PASSWORD: ""
global:
  namespace: "dev"
  imagePullPolicy: IfNotPresent
