replicas: 1
image:
  repository: eshop/webhooks
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
database:
  host: "{{ .Release.Name }}-catalogdb-postgresql-ha"
  name: webhooksdb
  username: postgres
  password: postgres
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
