global:
  registry: "docker.io/"
  namespace: dev

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
