apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: dev 
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq-headless
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      hostname: rabbitmq
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_DEFAULT_VHOST
          value: "/"
        - name: RABBITMQ_MNESIA_BASE
          value: /var/lib/rabbitmq/mnesia
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: "+sbwt none +sbwtdcpu none +sbwtdio none +stbt db"
        - name: RABBITMQ_CTL_ERL_ARGS
          value: "+P 1048576 +K true +A 128"
        - name: RABBITMQ_NODENAME
          value: rabbit@rabbitmq-0.rabbitmq-headless.dev.svc.cluster.local
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        volumeMounts:
        - name: rmq-data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
        livenessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "-q", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "-q", "ping"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: rmq-data
        persistentVolumeClaim:
          claimName: rmq-data-pvc
      - name: rabbitmq-config
        configMap:
          name: rabbitmq-config
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
