apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headlessName }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.service.amqpPort }}
    - name: management
      protocol: TCP
      port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
