apiVersion: v1
kind: Service
metadata:
  name: {{ include "eshop.fullname" . }}-headless
  namespace: {{ .Values.global.namespace | default "dev" }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range .Values.servicePorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "eshop.selectorLabels" . | nindent 4 }}
