apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eshop.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace | default "app" }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
type: Opaque
data:
  RABBITMQ_DEFAULT_PASS: {{ .Values.secret.RABBITMQ_DEFAULT_PASS | b64enc }}
