apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eshop.fullname" . }}
  namespace: {{ .Values.global.namespace | default "app" }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "eshop.fullname" . }}-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "eshop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eshop.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            {{- range .Values.containerPorts }}
            - containerPort: {{ .port }}
              name: {{ .name }}
            {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "eshop.fullname" . }}-secrets
                  key: RABBITMQ_DEFAULT_PASS
          volumeMounts:
            - name: rmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: rabbitmq-config
          configMap:
            name: {{ include "eshop.fullname" . }}-config
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
  volumeClaimTemplates:
    - metadata:
        name: rmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
