# kubernetes-manifests/catalogdb-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalogdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
