# kubernetes-manifests/rabbitmq/redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
  - port: 15672
    name: management
    targetPort: 15672
  - port: 5672
    name: amqp
    targetPort: 5672
