apiVersion: v1
kind: Service
metadata:
  name: {{ include "eshop.redis.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "eshop.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "eshop.redis.selectorLabels" . | nindent 4 }}
