apiVersion: v2
name: rabbitmq
description: A Helm chart for the RabbitMQ service in eShopOnContainers
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: rabbitmq
    version: "8.22.3"
    repository: "https://charts.bitnami.com/bitnami"
