replicas: 2

image:
  repository: ajkabs/catalog-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  - name: ConnectionStrings__catalogdb
    value: "Host=eshop-catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=yourpassword"

database:
  host: "{{ .Release.Name }}-catalogdb-postgresql-ha"
  name: catalogdb
  username: postgres
  password: postgres

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true