---
- name: Préparer les noeuds du cluster Kubernetes
  hosts: k8s_cluster
  become: true

  roles:
    - common
    - containerd
    - kubernetes
    
- name: Initialiser le Control Plane
  hosts: control_plane
  become: true

  roles:
    - control_plane
    - calico

- name: Joindre les Workers au cluster
  hosts: workers
  become: true

  roles:
    - worker

