apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "Redis-chart.fullname" . }}
  namespace: {{ .Values.global.namespace | default "dev" }}
  labels:
    {{- include "Redis-chart.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "Redis-chart.fullname" . }}-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "Redis-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "Redis-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          command: {{ .Values.command }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
