apiVersion: v1
kind: Service
metadata:
  name: order-processor
  namespace: dev 
spec:
  selector:
    app: order-processor
  ports:
  - protocol: TCP
    port: 16888
    targetPort: 16888
    nodePort: 31688
  type: NodePort
