apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: {{ .Values.namespace | default .Values.global.namespace }}
spec:
  selector:
    app: catalog-api
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
