apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "catalog.selectorLabels" . | nindent 4 }}
