# Configurations spécifiques pour Redis-chart
enabled: true
replicas: 1
image: redis:7.2-alpine
containerPort: 6379
servicePort: 6379

pvc:
  storage: 1Gi

livenessProbe:
  tcpSocket:
    port: 6379
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 6379
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"
    
command:
  - redis-server
  - --save ""
  - --appendonly no
  - --maxmemory 256mb
  - --maxmemory-policy allkeys-lru
