image:
  repository: redis
  tag: alpine
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 6379
password: "default-redis-password"
persistence:
  enabled: true
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  storageSize: "8Gi"
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

