postgresql-ha:
  service:
    port: 5432

  global:
    postgresql:
      username: postgres
      password: postgres
      database: catalogdb

  postgresql:
    replicaCount: 2

  pgpool:
    replicaCount: 2

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  storageSize: "1Gi"

resources:
  limits:
    cpu: "200m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true
