apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: dev 
spec:
  selector:
    app: identity-api
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30501
  type: NodePort
