apiVersion: v1
kind: Service
metadata:
  name: {{ include "eshop.rabbitmq.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "eshop.rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
  selector:
    {{- include "eshop.rabbitmq.selectorLabels" . | nindent 4 }}
