apiVersion: v1
kind: Service
metadata:
  name: {{ include "eshop.basket.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "eshop.basket.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "eshop.basket.selectorLabels" . | nindent 4 }}
