replicaCount: 1

namespace: dev

image:
  repository: ajkabs/basket-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5221

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:5221
  ASPNETCORE_HOSTING__ALLOWEDHOSTS: "*"
  ConnectionStrings__Redis: redis:6379,password=redis
  ConnectionStrings__EventBus: amqp://guest:guest@rabbitmq:5672
  Identity__Url: http://identity-api:5001
  DOTNET_READYTORUN: "1"
  DOTNET_TieredPGO: "1"
  DataProtection__Path: /app/keys
  ASPNETCORE_DataProtection__Keys: /app/keys
  ASPNETCORE_Kestrel__EndpointDefaults__Protocols: Http1AndHttp2

secret:
  REDIS_PASSWORD: redis
  EVENTBUS_CONNECTION: amqp://guest:guest@rabbitmq:5672

pvc:
  name: basket-data-protection
  size: 1Gi
  storageClassName: local-path

readinessProbe:
  path: /hc
  port: 5221
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

livenessProbe:
  path: /hc
  port: 5221
  initialDelaySeconds: 90
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

ingress:
  enabled: true
  host: basket.local
  path: /
  pathType: Prefix
  servicePort: 5221
