replicaCount: 1

image:
  repository: ajkabs/basket-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5221

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: "http://*:5221"
  ConnectionStrings__Redis: redis
  ConnectionStrings__EventBus: amqp://guest:guest@rabbitmq:5672
  Identity__Url: "http://identity-api:5001"
  DOTNET_READYTORUN: "1"
  DOTNET_TieredPGO: "1"

volumeMount:
  name: basket-data-protection
  mountPath: /app/keys

healthcheck:
  path: /hc
  port: 5221

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
