replicaCount: 1

namespace: dev

image:
  repository: ajkabs/basket-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5221

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://*:5221
  ASPNETCORE_HOSTING__ALLOWEDHOSTS: "*"
  ConnectionStrings__Redis: redis
  ConnectionStrings__EventBus: rabbitmq
  Identity__Url: http://identity-api:5001
  DOTNET_READYTORUN: "1"
  DOTNET_TieredPGO: "1"
  DataProtection__Path: /app/keys

secret:
  EVENTBUS_CONNECTION: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xOjU2NzI=

pvc:
  name: basket-data-protection
  size: 1Gi
  storageClassName: local-path

readinessProbe:
  exec:
    command: ["curl", "-f", "http://localhost:5221/hc"]
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10

livenessProbe:
  path: /hc
  port: 5221
  initialDelaySeconds: 90
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5

ingress:
  enabled: true
  host: basket.local
  path: /
  pathType: Prefix
  servicePort: 80
