replicaCount: 1

image:
  repository: ajkabs/basket-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5221

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: "http://*:5221"
  ConnectionStrings__Redis: redis
  Identity__Url: "http://identity-api:5001"
  DOTNET_READYTORUN: "1"
  DOTNET_TieredPGO: "1"
  # Note: suppression volontaire de DOTNET_DataProtection__PersistKeysToFileSystem

secretEnv:
  ConnectionStrings__EventBus: amqp://guest:guest@rabbitmq:5672

volumeMount:
  name: basket-data-protection
  mountPath: /root/.aspnet/DataProtection-Keys

pvc:
  name: basket-data-protection-pvc
  size: 100Mi

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

persistence:
  enabled: true
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  size: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
