<<<<<<< HEAD
replicas: 1

image:
  repository: ajkabs/basket-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5221
  nodePort: 30221

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://*:5221
  Identity__Url: http://identity-api:5001
  DOTNET_READYTORUN: "1"
  DOTNET_TieredPGO: "1"
  DataProtection__Path: /app/keys

=======
replicas: 2

image:
  repository: ajkabs/basket-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

redis:
  host: "{{ .Release.Name }}-redis"
  port: 6379

>>>>>>> 713ef402ffd6afc8580349fe1e1b5402583fca12
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

<<<<<<< HEAD
pvc:
  storage: "100Mi"

secrets:
  redisHost: "redis"
  eventBusConnection: "amqp://guest:guest@rabbitmq:5672"
=======
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true
>>>>>>> 713ef402ffd6afc8580349fe1e1b5402583fca12
