replicas: 1

image:
  repository: ajkabs/basket-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5221
  nodePort: 30221

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://*:5221
  Identity__Url: http://identity-api:5001
  DOTNET_READYTORUN: "1"
  DOTNET_TieredPGO: "1"
  DataProtection__Path: /app/keys

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

pvc:
  storage: "100Mi"

secrets:
  redisHost: "redis"
  eventBusConnection: "amqp://guest:guest@rabbitmq:5672"
