# Configurations spécifiques pour Ordering-chart
enabled: true
replicas: 1
image: ajkabs/ordering-api:latest
containerPort: 8080
servicePort: 80

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://*:8080
  RabbitMQ__Host: rabbitmq
  RabbitMQ__Port: "5672"
  Identity__Url: http://identity-api:5001

secret:
  ORDERINGDB_CONNECTION: "" # Fournir en base64 lors du déploiement
  EVENTBUS_CONNECTION: "" # Fournir en base64 lors du déploiement

pvc:
  storage: 1Gi

livenessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5
  
resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "600m"
    memory: "512Mi"
