apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "Webapp-chart.fullname" . }}
  namespace: {{ .Values.global.namespace | default "dev" }}
  labels:
    {{- include "Webapp-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "Webapp-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "Webapp-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          command: ["/bin/sh", "-c", "./wait-for-it.sh identity-api:5001 -- ./wait-for-it.sh catalog-api:80 -- ./wait-for-it.sh basket-api:5221 -- ./wait-for-it.sh ordering-api:8080 -- ./wait-for-it.sh rabbitmq:5672 -- dotnet Webapp.dll"]
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: EventBus__Username
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: EVENTBUS_USERNAME
            - name: EventBus__Password
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: EVENTBUS_PASSWORD
            - name: ConnectionStrings__EventBus
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: EVENTBUS_CONNECTION
          volumeMounts:
            - name: webapp-data-protection
              mountPath: /app/keys
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: webapp-data-protection
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
