apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secrets
  namespace: dev 
type: Opaque
data:
  CATALOGDB_CONNECTION: SG9zdD1jYXRhbG9nZGI7UG9ydD01NDMyO0RhdGFiYXNlPWNhdGFsb2dkYjtVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPXBhc3N3b3JkOw== # "Host=catalogdb;Port=5432;Database=catalogdb;User Id=postgres;Password=password;" en base64
  EVENTBUS_CONNECTION: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xOjU2NzI= # "amqp://guest:guest@rabbitmq:5672" en base64
