apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: dev 
spec:
  selector:
    app: catalog-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30222
  type: NodePort
