apiVersion: v1
kind: Service
metadata:
  name: ordering-api
  namespace: dev 
spec:
  selector:
    app: ordering-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30224
  type: NodePort
