apiVersion: v1
kind: PersistentVolume
metadata:
  name: basket-data-protection
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/data/basket  # Assure-toi que ce dossier existe sur ton node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - aka-thk  # Remplace par le nom exact de ton node (kubectl get nodes)
