apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "basket.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      }
    }
