apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basket.fullname" . }}
  namespace: {{ .Values.global.namespace | default "dev" }}
  labels:
    {{- include "basket.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "basket.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "basket.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: basket-api
          image: "{{ .Values.global.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
            - name: ASPNETCORE_URLS
              value: {{ .Values.env.ASPNETCORE_URLS | quote }}
            - name: ConnectionStrings__Redis
              value: {{ .Values.secrets.redisHost | quote }}
            - name: ConnectionStrings__EventBus
              valueFrom:
                secretKeyRef:
                  name: {{ include "basket.fullname" . }}-secret
                  key: eventBusConnection
            - name: Identity__Url
              value: {{ .Values.env.Identity__Url | quote }}
            - name: DOTNET_READYTORUN
              value: {{ .Values.env.DOTNET_READYTORUN | quote }}
            - name: DOTNET_TieredPGO
              value: {{ .Values.env.DOTNET_TieredPGO | quote }}
            - name: DataProtection__Path
              value: {{ .Values.env.DataProtection__Path | quote }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/appsettings.json
              subPath: appsettings.json
            - name: basket-data-protection
              mountPath: /app/keys
          command:
            - "/bin/sh"
            - "-c"
            - "./wait-for-it.sh redis:6379 -- ./wait-for-it.sh rabbitmq:5672 -- dotnet Basket.API.dll"
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "basket.fullname" . }}-config
        - name: basket-data-protection
          persistentVolumeClaim:
            claimName: basket-data-protection-pvc
