apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basket.fullname" . }}
<<<<<<< HEAD
  namespace: {{ .Values.global.namespace | default "dev" }}
=======
  namespace: {{ .Values.global.namespace }}
>>>>>>> 713ef402ffd6afc8580349fe1e1b5402583fca12
  labels:
    {{- include "basket.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "basket.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "basket.selectorLabels" . | nindent 8 }}
<<<<<<< HEAD
=======
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
>>>>>>> 713ef402ffd6afc8580349fe1e1b5402583fca12
    spec:
      containers:
        - name: basket-api
          image: "{{ .Values.global.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
<<<<<<< HEAD
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
            - name: ASPNETCORE_URLS
              value: {{ .Values.env.ASPNETCORE_URLS | quote }}
            - name: ConnectionStrings__Redis
              value: {{ .Values.secrets.redisHost | quote }}
            - name: ConnectionStrings__EventBus
              valueFrom:
                secretKeyRef:
                  name: {{ include "basket.fullname" . }}-secret
                  key: eventBusConnection
            - name: Identity__Url
              value: {{ .Values.env.Identity__Url | quote }}
            - name: DOTNET_READYTORUN
              value: {{ .Values.env.DOTNET_READYTORUN | quote }}
            - name: DOTNET_TieredPGO
              value: {{ .Values.env.DOTNET_TieredPGO | quote }}
            - name: DataProtection__Path
              value: {{ .Values.env.DataProtection__Path | quote }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/appsettings.json
              subPath: appsettings.json
            - name: basket-data-protection
              mountPath: /app/keys
          command:
            - "/bin/sh"
            - "-c"
            - "./wait-for-it.sh redis:6379 -- ./wait-for-it.sh rabbitmq:5672 -- dotnet Basket.API.dll"
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
=======
            - containerPort: 80
          env:
            - name: Redis__Host
              valueFrom:
                secretKeyRef:
                  name: {{ include "basket.fullname" . }}-secret
                  key: redisHost
            - name: Redis__Port
              valueFrom:
                secretKeyRef:
                  name: {{ include "basket.fullname" . }}-secret
                  key: redisPort
          volumeMounts:
            - name: config-volume
              mountPath: "/app/config/appsettings.json"
              subPath: appsettings.json
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
>>>>>>> 713ef402ffd6afc8580349fe1e1b5402583fca12
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
<<<<<<< HEAD
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
=======
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
>>>>>>> 713ef402ffd6afc8580349fe1e1b5402583fca12
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "basket.fullname" . }}-config
<<<<<<< HEAD
        - name: basket-data-protection
          persistentVolumeClaim:
            claimName: basket-data-protection-pvc
=======
>>>>>>> 713ef402ffd6afc8580349fe1e1b5402583fca12
