apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basket.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "basket.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "basket.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "basket.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: basket-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
            - name: ASPNETCORE_URLS
              value: {{ .Values.env.ASPNETCORE_URLS | quote }}
            - name: ConnectionStrings__Redis
              value: {{ .Values.env.ConnectionStrings__Redis | quote }}
            - name: ConnectionStrings__EventBus
              valueFrom:
                secretKeyRef:
                  name: basket-api-secrets
                  key: EVENTBUS_CONNECTION
            - name: Identity__Url
              value: {{ .Values.env.Identity__Url | quote }}
            - name: DOTNET_READYTORUN
              value: {{ .Values.env.DOTNET_READYTORUN | quote }}
            - name: DOTNET_TieredPGO
              value: {{ .Values.env.DOTNET_TieredPGO | quote }}
            - name: DataProtection__Path
              value: {{ .Values.env.DataProtection__Path | quote }}
          volumeMounts:
            - name: basket-data-protection
              mountPath: {{ .Values.env.DataProtection__Path }}
          command:
            ["/bin/sh", "-c", "./wait-for-it.sh redis:6379 -- ./wait-for-it.sh rabbitmq:5672 -- dotnet Basket.API.dll"]
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: basket-data-protection
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
