apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: basket
  template:
    metadata:
      labels:
        app: basket
    spec:
      containers:
        - name: basket
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: basket-config
          volumeMounts:
            - name: {{ .Values.volumeMount.name }}
              mountPath: {{ .Values.volumeMount.mountPath }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: {{ .Values.volumeMount.name }}
          emptyDir: {}
      restartPolicy: Always
