apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basket-data-protection-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
