apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basket.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
<<<<<<< HEAD
type: Opaque
stringData:
  redisHost: {{ .Values.secrets.redisHost }}
  redisPort: {{ .Values.secrets.redisPort }}
  rabbitmqHost: {{ .Values.secrets.rabbitmqHost }}
  rabbitmqPort: {{ .Values.secrets.rabbitmqPort }}
  rabbitmqUsername: {{ .Values.secrets.rabbitmqUsername }}
  rabbitmqPassword: {{ .Values.secrets.rabbitmqPassword }}
=======
  labels:
{{ include "basket.labels" . | indent 4 }}
type: Opaque
stringData:
  redisHost: {{ .Values.redis.host | quote }}
  redisPort: {{ .Values.redis.port | quote }}
>>>>>>> 713ef402ffd6afc8580349fe1e1b5402583fca12
