apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eshop.basket.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "eshop.basket.labels" . | nindent 4 }}
type: Opaque
stringData:
  redisHost: {{ .Values.redis.host }}
  redisPort: "{{ .Values.redis.port }}"
