apiVersion: v1
kind: Secret
metadata:
  name: basket-api-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  EVENTBUS_CONNECTION: {{ .Values.secret.EVENTBUS_CONNECTION | b64enc }}
  REDIS_PASSWORD: {{ .Values.secret.REDIS_PASSWORD | b64enc }}