apiVersion: v1
kind: Service
metadata:
  name: basket-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: basket-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
