# helm-chart/charts/basket/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: basket-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: basket-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}         # port: 5221
      targetPort: {{ .Values.service.port }}   # targetPort: 5221
  type: ClusterIP
