apiVersion: v1
kind: Service
metadata:
  name: {{ include "basket.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "basket.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "basket.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
