apiVersion: v1
kind: Service
metadata:
  name: {{ include "basket.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "basket.labels" . | nindent 4 }}
spec:
<<<<<<< HEAD
  selector:
    {{- include "basket.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
=======
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "basket.selectorLabels" . | nindent 4 }}
>>>>>>> 713ef402ffd6afc8580349fe1e1b5402583fca12
