# kubernetes-manifests/basket-api/basket-api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: basket-api
spec:
  selector:
    app: basket-api
  ports:
    - protocol: TCP
      port: 5104
      targetPort: 5104

