# kubernetes-manifests/basket-api/basket-api-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basket-dataprotection-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi