apiVersion: v1
kind: Secret
metadata:
  name: {{ include "CatalogDB-chart.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace | default "dev" }}
  labels:
    {{- include "CatalogDB-chart.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD }}
