# Configurations spécifiques pour RabbitMQ
enabled: true
replicas: 1
image: rabbitmq:3.12-management-alpine

containerPorts:
  - name: amqp
    port: 5672
  - name: management
    port: 8080

servicePort: 5672
managementPort: 80

env:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_MNESIA_BASE: /var/lib/rabbitmq/mnesia
  RABBITMQ_DEFAULT_VHOST: /
  RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "+sbwt none +sbwtdcpu none +sbwtdio none +stbt db"
  RABBITMQ_CTL_ERL_ARGS: "+P 1048576 +K true +A 128"
  RABBITMQ_NODENAME: rabbit@rabbitmq

secret:
  RABBITMQ_DEFAULT_PASS: "" # Fournir en base64 lors du déploiement

pvc:
  storage: 1Gi

livenessProbe:
  tcpSocket:
    port: 5672
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 5672
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
