replicas: 1
image: ankane/pgvector:latest
imagePullPolicy: IfNotPresent
containerPort: 5432
servicePort: 5432
serviceType: ClusterIP

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

livenessProbe:
  tcpSocket:
    port: 5432
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  tcpSocket:
    port: 5432
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

persistence:
  enabled: true
  storageClass: standard
  size: 1Gi

env:
  POSTGRES_DB: catalogdb
  POSTGRES_USER: postgres

secret:
  POSTGRES_PASSWORD: mySecurePassword123  # 🔐 Ne jamais laisser vide

global:
  namespace: dev
  imagePullPolicy: IfNotPresent
