apiVersion: v1
kind: Service
metadata:
  name: catalogdb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: catalogdb
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
