apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eshop.fullname" . }}
  namespace: {{ .Values.global.namespace | default "dev" }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "eshop.fullname" . }}-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "eshop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eshop.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: {{- toYaml .Values.command | nindent 12 }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: postgres
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "eshop.fullname" . }}-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init-db.sh
              subPath: init-db.sh
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: init-script
          configMap:
            name: {{ include "eshop.fullname" . }}-init-script
            items:
              - key: init-db.sh
                path: init-db.sh
                mode: 0755
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.global.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
