apiVersion: v1
kind: Service
metadata:
  name: payment-processor
  namespace: dev 
spec:
  selector:
    app: payment-processor
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30226
  type: NodePort
