enabled: true
replicas: 1
image: ordering-api:latest
imagePullPolicy: IfNotPresent
containerPort: 8080
servicePort: 8080
serviceType: ClusterIP

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

persistence:
  enabled: true
  storageClass: standard
  size: 100Mi

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: "http://*:8080"
  RabbitMQ__Host: rabbitmq
  RabbitMQ__Port: "5672"

initContainers:
  - name: wait-for-dependencies
    image: busybox:latest
    command:
      - "/bin/sh"
      - "-c"
      - >
        until nslookup eshop-rabbitmq &&
              nslookup eshop-catalogdb &&
              nslookup eshop-identity;
        do echo "waiting for dependencies"; sleep 2; done;

secret:
  ORDERINGDB_CONNECTION: ""
  EVENTBUS_CONNECTION: ""
  IDENTITY_URL: ""

global:
  namespace: "app"
  imagePullPolicy: IfNotPresent
