# Configurations spécifiques pour Identity-chart
enabled: true
replicas: 1
image: ajkabs/identity-api:latest
containerPort: 5001
servicePort: 80

env:
  ASPNETCORE_ENVIRONMENT: Development
  MauiCallback: http://identity-api:5001/callback
  ASPNETCORE_URLS: http://*:5001
  WebAppClient: http://localhost:16889

secret:
  IDENTITYDB_CONNECTION: "" # Fournir en base64 lors du déploiement
  EVENTBUS_CONNECTION: "" # Fournir en base64 lors du déploiement

pvc:
  storage: 1Gi

livenessProbe:
  path: /health
  port: 5001
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  path: /health
  port: 5001
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5
  
resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
