apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eshop.orderprocessor.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "eshop.orderprocessor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "eshop.orderprocessor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eshop.orderprocessor.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5672"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: orderprocessor
          image: "{{ .Values.global.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: {{ include "eshop.orderprocessor.fullname" . }}-secret
                  key: rabbitmqUsername
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: {{ include "eshop.orderprocessor.fullname" . }}-secret
                  key: rabbitmqPassword
          volumeMounts:
            - name: config-volume
              mountPath: "/app/config/appsettings.json"
              subPath: appsettings.json
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "eshop.orderprocessor.fullname" . }}-config
