image:
  repository: redis
  tag: alpine
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 6379
password: "default-redis-password"
persistence:
  enabled: true
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  storageSize: "1Gi"
resources:
  limits:
    cpu: "100m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "128Mi"

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true
