image:
  repository: redis
  tag: alpine
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 6379
password: "default-redis-password"
persistence:
  enabled: true
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
<<<<<<< HEAD
  storageSize: "1Gi"
=======
  storageSize: "8Gi"
>>>>>>> 713ef402ffd6afc8580349fe1e1b5402583fca12
resources:
  limits:
    cpu: "100m"
    memory: "256Mi"
<<<<<<< HEAD
  requests:
    cpu: "50m"
    memory: "128Mi"
=======
>>>>>>> 713ef402ffd6afc8580349fe1e1b5402583fca12

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true
