apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eshop.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace | default "dev" }}
  labels:
    {{- include "eshop.labels" . | nindent 4 }}
type: Opaque
data:
  WEBHOOKSDB_CONNECTION: {{ .Values.secret.WEBHOOKSDB_CONNECTION | b64enc }}
  EVENTBUS_CONNECTION: {{ .Values.secret.EVENTBUS_CONNECTION | b64enc }}
